"""phase1_geography_fleet_schedule

Revision ID: 99565cac3599
Revises: 
Create Date: 2026-07-29 22:40:02.751856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99565cac3599'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('max_range_km', sa.Integer(), nullable=True),
    sa.Column('cruise_speed_kmh', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aircraft_types')),
    sa.UniqueConstraint('iata_code', name=op.f('uq_aircraft_types_iata_code'))
    )
    op.create_table('airlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iata_code', sa.String(length=2), nullable=False),
    sa.Column('icao_code', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_airlines')),
    sa.UniqueConstraint('iata_code', name=op.f('uq_airlines_iata_code')),
    sa.UniqueConstraint('icao_code', name=op.f('uq_airlines_icao_code'))
    )
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('icao_code', sa.String(length=4), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('elevation_ft', sa.Integer(), nullable=True),
    sa.Column('tz', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_airports')),
    sa.UniqueConstraint('iata_code', name=op.f('uq_airports_iata_code')),
    sa.UniqueConstraint('icao_code', name=op.f('uq_airports_icao_code'))
    )
    op.create_table('aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=10), nullable=False),
    sa.Column('aircraft_type_id', sa.Integer(), nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_type_id'], ['aircraft_types.id'], name=op.f('fk_aircraft_aircraft_type_id_aircraft_types')),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], name=op.f('fk_aircraft_airline_id_airlines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aircraft')),
    sa.UniqueConstraint('registration', name=op.f('uq_aircraft_registration'))
    )
    op.create_table('cabin_layouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_type_id'], ['aircraft_types.id'], name=op.f('fk_cabin_layouts_aircraft_type_id_aircraft_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cabin_layouts')),
    sa.UniqueConstraint('aircraft_type_id', 'name', name=op.f('uq_cabin_layouts_aircraft_type_id'))
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], name=op.f('fk_routes_airline_id_airlines')),
    sa.ForeignKeyConstraint(['destination_id'], ['airports.id'], name=op.f('fk_routes_destination_id_airports')),
    sa.ForeignKeyConstraint(['origin_id'], ['airports.id'], name=op.f('fk_routes_origin_id_airports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes')),
    sa.UniqueConstraint('airline_id', 'origin_id', 'destination_id', name=op.f('uq_routes_airline_id'))
    )
    op.create_table('scheduled_flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=6), nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('days_of_week', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('aircraft_type_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_type_id'], ['aircraft_types.id'], name=op.f('fk_scheduled_flights_aircraft_type_id_aircraft_types')),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], name=op.f('fk_scheduled_flights_airline_id_airlines')),
    sa.ForeignKeyConstraint(['destination_id'], ['airports.id'], name=op.f('fk_scheduled_flights_destination_id_airports')),
    sa.ForeignKeyConstraint(['origin_id'], ['airports.id'], name=op.f('fk_scheduled_flights_origin_id_airports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_flights'))
    )
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_flight_id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=6), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=True),
    sa.Column('cabin_layout_id', sa.Integer(), nullable=True),
    sa.Column('departure_scheduled', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_scheduled', sa.DateTime(timezone=True), nullable=False),
    sa.Column('departure_actual', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_actual', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='scheduled', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], name=op.f('fk_flights_aircraft_id_aircraft')),
    sa.ForeignKeyConstraint(['cabin_layout_id'], ['cabin_layouts.id'], name=op.f('fk_flights_cabin_layout_id_cabin_layouts')),
    sa.ForeignKeyConstraint(['scheduled_flight_id'], ['scheduled_flights.id'], name=op.f('fk_flights_scheduled_flight_id_scheduled_flights')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flights')),
    sa.UniqueConstraint('scheduled_flight_id', 'service_date', name=op.f('uq_flights_scheduled_flight_id'))
    )
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cabin_layout_id', sa.Integer(), nullable=False),
    sa.Column('seat_no', sa.String(length=4), nullable=False),
    sa.Column('cabin_class', sa.String(length=10), nullable=False),
    sa.Column('row_num', sa.Integer(), nullable=False),
    sa.Column('column_letter', sa.String(length=1), nullable=False),
    sa.Column('is_window', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_aisle', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_exit_row', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cabin_layout_id'], ['cabin_layouts.id'], name=op.f('fk_seats_cabin_layout_id_cabin_layouts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seats')),
    sa.UniqueConstraint('cabin_layout_id', 'seat_no', name=op.f('uq_seats_cabin_layout_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seats')
    op.drop_table('flights')
    op.drop_table('scheduled_flights')
    op.drop_table('routes')
    op.drop_table('cabin_layouts')
    op.drop_table('aircraft')
    op.drop_table('airports')
    op.drop_table('airlines')
    op.drop_table('aircraft_types')
    # ### end Alembic commands ###
